### PR TITLE
add an option to load the app inside an html component

### PR DESCRIPTION
**Pull request by sergiomcalzada**
Tested in local and worked.

### CODE REVIEW

**Comment by sergiomcalzada** [comment]
@robinComa did you reviewed the pull request?

**Comment by robinComa** [comment]
Sorry for the delay I merge It, I update the npm version as soon as possible

**Comment by sergiomcalzada** [comment]
Waiting for it to integrate inside my project 😎

**Comment by robinComa** [comment]
Done ! Sorry for the delay, the new version is [0.4.2](https://www.npmjs.com/package/single-spa-angular-cli)

**Pull request merged**
