### PR TITLE
Added Option to Prevent Unmount

### PR DESCRIPTION
**Pull request by bfaulk96**
Added an option to intentionally prevent app unmounting by specifying a variable preventUnmount in the single spa props.customProps. An example of this:
```
registerApplication(
  application.name,
  (() => {
    const lifecycles = loader({
      name: application.name,
      selector: application.selector,
      baseHref: application.baseHref,
    });
    return {
      bootstrap: [lifecycles.bootstrap],
      mount: [lifecycles.mount],
      unmount: [lifecycles.unmount],
      unload: [lifecycles.unload],
    };
  })(),
  router.matchRoute(application.matchRoute, application.isDefaultApp),
  {
    preventUnmount: true
  }
);
```
This is useful because in some cases, the child apps make API calls and/or retrieve data, which can take some time. If we unmount the child apps, they have to make the API calls again next time they mount, repeating that initial wasted time. If we leave the child apps mounted even after navigating off of them, once we navigate back to them we don't necessarily need to retrieve the data again.

### CODE REVIEW

**Comment by bfaulk96** [comment]
This fixes the issue #25

**Comment by bfaulk96** [comment]
This won't change anything that is currently in place, it only adds the option to specify not to unmount in the customProps. This can be ignored if someone doesn't want to use the option.

**Comment by robinComa** [comment]
Thanks for the PR, could you please resolve the confilts?

Regards,

**Comment by bfaulk96** [comment]
Updated 👍

**Comment by bfaulk96** [comment]
Would you mind creating a new version for NPM after merging this update? My team would much appreciate it :)

**Comment by TheMcMurder** [comment]
This is interesting. The library single-spa doesn't currently support this feature. Are you implementing `prevent-unmount` inside this helper library? I'm not sure this approach is going to be good long term, would you please help me understand why this is necessary?

**Comment by bfaulk96** [comment]
You are correct, single-spa itself does not currently support this feature. Yes, I'm implementing the prevent-unmount inside of this helper library. I agree that this approach may not be the best long-term, however, it also won't hurt anything (as these changes have no effect on this library unless that option is specified). This is necessary for my team because child apps have to retrieve data independent of the parent app (so we can't just keep the data in the parent and propagate it down, unfortunately). If we were to unmount and mount every time the page takes the initial load time (which, for us can be 3-5 seconds) every single time we navigate back to a child route.
My team has been using a custom version of this repo pulled locally for several months now, but seeing as that is bad practice, I wanted to merge a real solution that doesn't hurt the existing library but can help any teams in a similar position as mine.

**Comment by filoxo** [comment]
Rather than potentially introducing performance problems for yourself and anyone else who uses this helper this way, it seems that you need to change your API to support caching a response instead (see [RESTful API caching](https://restfulapi.net/caching/), and this [HTTP caching guide by Google](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching)). This way data that's already been retrieved can be cached and reused without any changes to your front-end and this helper library.

**Comment by filoxo** [comment]
Also, I don't believe maintaining a separate fork that does exactly what you want is seen a bad practice. We'd probably encourage that since this feature may not be accepted.

**Comment by joeldenning** [comment]
Should this PR be closed. Issue #25 was discussed in pretty good detail and i think it was decided that it would be best to go a different direction with this.

**Pull request closed without merging**
